
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:  ubuntu-20.04
    
    steps:
      - name: Set up Python
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --no-root
      - name: Run tests
        run: |
          poetry run pytest

      # Add more steps for your build process here
