- name: Activate Python 3.10.2
  uses: actions/setup-python@v2
  with:
    python-version: '3.10.2'

- name: Install dependencies
  run: |
    python -m pip install --verbose pip
    pip install --verbose poetry
    poetry install

- name: Run tests
  run: |
    poetry run pytest
